Revert "PD#100922:
amports: Copy Y and UV component in separate operations"

Below commit break compile.

This reverts commit
26f0ebd3ef11ee58128f6080dda326610e18bb22.


drivers/amlogic/amports/video.c: In function ‘vf_keep_current’:
drivers/amlogic/amports/video.c:4054:79: error: expected ‘)’ before 
‘{’ token
drivers/amlogic/amports/video.c:4173:1: error: expected expression 
before ‘}’ token
drivers/amlogic/amports/video.c:4015:26: error: unused variable ‘cd’ 
[-Werror=unused-variable]
drivers/amlogic/amports/video.c:4015:22: error: unused variable ‘cs2’ 
[-Werror=unused-variable]
drivers/amlogic/amports/video.c:4015:18: error: unused variable ‘cs1’ 
[-Werror=unused-variable]
drivers/amlogic/amports/video.c:4015:14: error: unused variable ‘cs0’ 
[-Werror=unused-variable]
drivers/amlogic/amports/video.c: At top level:
drivers/amlogic/amports/video.c:1201:13: error: ‘ge2d_keeplastframe_
block’ defined but not used [-Werror=unused-function]
drivers/amlogic/amports/video.c:3997:12: error: ‘canvas_dup’ defined 
but not used [-Werror=unused-function]
drivers/amlogic/amports/video.c: In function ‘vf_keep_current’:
drivers/amlogic/amports/video.c:4173:1: error: control reaches end of 
non-void function [-Werror=return-type]
cc1: all warnings being treated as errors


Change-Id: If79ae3665ea99568692139186445ac6e31c21c6d