remote: fix array out of bounds issue
This issue is reported by gcc 4.8 Warning aggressive-loop-optimizations

Below loop has the array out of bounds risk/error. Because it used first
level array index as the loop index limitation. But i is used as second 
level array index.

remote_main.c:680:33: error: iteration 6u invokes undefined behavior 
   [-Werror=aggressive-loop-optimizations]
   mouse_map[remote->map_num][i] = 0xffff;
                                 ^
remote_main.c:679:2: note: containing loop
  for (i = 0; i < ARRAY_SIZE(mouse_map); i++) {
  ^

Change-Id: If515caf93dad52dc486ac256e577219fcb297225